---
title: "Projects"
---
  
[**Last Updated Time**: `r Sys.time()`]{style="float:right"}  
  
  

***  
<br>  

## [Self-Evaluation Project](https://alin-96.github.io/selfeval_main.html)

<font size="3">   Towards the end of my military service, I tried to find ways to maintain a high-disciplinary lifestyle even after my release. After much contemplation, I decided to develop a grading system for my day-to-day life, which sprouted from the concept of math exams. The graded exams allow us to improve our mathematical knowledge by analyzing our weaknesses and strengths. Thus, by utilizing quantifiable variables that best represent the fullness of my lifestyle and by implementing various mathematical models, I was able to construct an effective grading system for my day-to-day life. 
    
  The self-evaluation project comprises three main procedures: collecting meaningful data, applying statistical analysis, and visualizing indicative findings in daily life. The goal is to find numerous insights and unique patterns with over 500 days' worth of data using R. Also, a more comprehensive understanding of the lifestyle will be obtained by utilizing advanced statistical concepts such as linear regressions and various correlation tests. Ultimately, these findings will provide better guidance for me to achieve healthier life patterns in the future.</font>


<br>  
<br>  

## [Happiness Project](https://alin-96.github.io/happiness_main.html)

<font size="3">   The data was collected from Gallup World Poll. Their survey consisted of questions that asked participants to rank their own life on a Cantril ladder with a scale from 1 to 10, 10 being the best ideal way of living and 0 being the worst. This data set focuses on the happiness score of each country, which ranges from 0 to 10. Each country is ranked based on that averaged happiness score for participants. The team recorded scores for these factors: economy or GDP per Capita, family or social support, health or life expectancy, and freedom to help explain the happiness score of each country. </font>

<font size = "5">**Goals**</font>

  1. <font size = "3">**Data Manipulations**
      - Merge the data with 2 other data sets
          - Death Data: Total annual number of deaths by country/risk factor
          - UN Country Data: Indicators of all the countries present in UN Data
  2. **Various visualizations using ggplot2**
      - Happiness Rankings throughout countries
      - Change in happiness rankings
  3. **Statistical Analysis**
      - Linear Regressions & Multiple Regressions
      - Clustering
      - Time Series</font>

