---
title: "Interactive Visualization"
author: "Andy"
date: "3/24/2022"
output: html_document
---

```{r}
library(tidyverse)
library(plotly)
library(gganimate)
library(gifski) # for PCs
library(transformr) # for manipulating polygons and paths
library(magick) # for animation rendering
library(htmltools) # for html rendering
theme_set(theme_bw())
```

```{r}
# gganimate
p <- ggplot(data = mtcars,
       mapping = aes(x = factor(cyl), y = mpg)) +
  geom_boxplot()

p

```

```{r}
p + facet_wrap(~gear)
```


```{r}
# transition_states() function

my_anim <- p + 
  transition_states(gear)

my_anim
```

```{r}
# Adjust the transition time

my_anim2 <- p + 
  transition_states(gear,
    transition_length = 3,  # relative length
    state_length = 2)  # relative length

my_anim2
```

```{r}
# Cooperative Congressional Election Survey

cces <- read_csv(url("https://bcdanl.github.io/data/cces.csv"))
cces <- cces %>% 
  mutate(party = recode(dem,`1`="Democrat",`0`="Republican"))

cong_dat <- cces %>% 
  group_by(year, party) %>%
  summarise( seats =n())

cong_dat
```

```{r}
# Visualize
p <- ggplot(cong_dat, 
            aes(x = year, y= seats, 
                fill = party)) +
  geom_bar(stat="identity") +
  geom_hline(yintercept = 217) +  # threshold for having a majority of seats in the house.
  scale_fill_manual(values=c("blue","red"))

p
```

```{r}
# transition_time() function
anim2 <- p + transition_time(year)

anim2
```

```{r}
# Seniority vs all_pass
  # Variable seniority is about how long a member has been in Congress.
  # Variable all_pass is about how many bills a member passed


p <- ggplot() + 
  geom_jitter(data = filter(cces, 
                            congress==115 & party=="Democrat"),
              aes(x = seniority, y = all_pass,
                  color = party) ) +
  geom_jitter(data = filter(cces, 
                            congress==115 & party=="Republican"),
              aes(x = seniority, y = all_pass,
                  color = party) ) +
  geom_smooth(data = filter(cces, 
                            congress==115 & party=="Democrat"),
              aes(x = seniority, y = all_pass,
                  color = party) ) +
  geom_smooth(data = filter(cces, 
                            congress==115 & party=="Republican"),
              aes(x = seniority, y = all_pass,
                  color = party) ) +
  scale_color_manual(values=c("blue","red"))

p
```

```{r}
# Visualize using transition_layers()
anim2 <- p + transition_layers()

anim2
```

```{r}
# enter_*(), exit_*(), and *_fade() functions
anim <- ggplot(mtcars, aes(factor(cyl), mpg)) +
  geom_boxplot() +
  transition_states(factor(gear))

# Fade-in, fade-out
anim1 <- anim +
  enter_fade() +
  exit_fade()

anim1

```

```{r}
# shadow_*() and shadow_wake() functions
p <- ggplot(cong_dat,
                aes(x = year, y = seats, fill = party)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = 217) +
  scale_fill_manual(values = c("blue","red"))


anim3 <- p + transition_time(year) +
   shadow_wake(wake_length = 1,
              alpha = TRUE,
              wrap = TRUE)

anim3
```

```{r}
# How to save the animation
anim_save("test.gif", animation = anim3)
```










```{r}
# Plotly Module

# Make some noisily increasing data
dat <- data.frame(cond = rep(c("A", "B"), each = 10),
                  xvar = 1:20 + rnorm(20, sd=3),
                  yvar = 1:20 + rnorm(20, sd=3))

p <- ggplot(dat, aes(x = xvar, y = yvar)) +
  geom_point(shape=1)      # Use hollow circles
fig <- ggplotly(p)
fig
```


```{r}
# See the efficiency of the legislators
  # variable les is a score for legislative effectiveness

p <- ggplot(cces, aes(x = seniority, y = les,
                      color = party))+
  geom_point()+
  scale_color_manual(values=c("blue","red")) +
  labs(x = "Seniority", y = "Leg. Effectiveness")

p
```

```{r}
# animate using frame feature
p <- ggplot(cces, aes(x = seniority, y = les,
                      color = party,
                      frame = year) ) + #this animates the figure
  geom_point()+
  scale_color_manual(values = c("blue","red")) +
  labs(x = "Seniority", y = "Leg. Effectiveness")

p1 <- ggplotly(p)
p1
```

```{r}
p <- ggplot(cces, aes(x = seniority, y = les,
                      color = party,
                      frame = year,
                      ids = thomas_name) ) + # this adds the object constancy
  geom_point()+
  scale_color_manual(values = c("blue","red")) +
  labs(x = "Seniority", y = "Leg. Effectiveness")

p1 <- ggplotly(p)
p1
```

```{r}
# How to save the ggplotly animation
htmlwidgets::saveWidget(p1, "fig.html")
```

