---
title: "Draw Maps"
author: "Andy"
date: "3/1/2022"
output: html_document
---

```{r}
# Required packages
library(tidyverse)
library(socviz)
library(ggthemes)
theme_set(theme_minimal())
```

```{r}
election %>% select(state, total_vote,
                    r_points, pct_trump, party, census) %>%
    sample_n(5)
```


```{r}
party_colors <- c("#2E74C0", "#CB454A")  # Hex color codes for Dem Blue and Rep Red
p0 <- ggplot(data = subset(election, st %nin% "DC"),
             mapping = aes(x = r_points,
                           y = reorder(state, r_points),
                           color = party))

p1 <- p0 + geom_vline(xintercept = 0, color = "gray30") +
    geom_point(size = 2)

p2 <- p1 + scale_color_manual(values = party_colors)

p3 <- p2 + scale_x_continuous(breaks = c(-30, -20, -10, 0, 10, 20, 30, 40),
                              labels = c("30\n (Clinton)", "20", "10", "0",
                                         "10", "20", "30", "40\n(Trump)"))

p3 + facet_wrap(~ census, ncol=1, scales="free_y") +
     guides(color = "none") + labs(x = "Point Margin", y = "") +
     theme(axis.text=element_text(size=8))
```


```{r}
us_states <- map_data("state")
head(us_states)
```

```{r}
p <- ggplot(data = us_states,
            mapping = aes(x = long, y = lat,
                          group = group))

p + geom_polygon(fill = "white", color = "black")

```

