---
title: "Data Visualization Notes"
author: "YOUR_NAME"
date: "2022-02-08"
output: html_document
---


```{r}
library(tidyverse)
library(skimr)   # a better summary of data frame
library(scales)  # scales for ggplot
library(gapminder) # gapminder data
library(socviz)  # data for visualization practice
library(ggrepel)  # for text on plot, geom_text_repel(), geom_label_repel()

```


```{r}

glimpse(gss_sm)
skim(gss_sm)
view(gss_sm)

p <- ggplot(data = gss_sm,
            mapping = aes(x = bigregion, fill = religion))
p + geom_bar(position = "fill")

p <- ggplot(data = gss_sm,
            mapping = aes(x = bigregion ))
p + geom_bar(position = "dodge",
             mapping = aes(y = ..prop.., group = religion)) +
    facet_wrap(~ religion, ncol = 1)
```

```{r}
# %>% Operator
# A pipeline is typically a series of operations that do one or more of four things:
###  group_by() ###
  #Group the data into the nested structure we want for our summary, such as “Religion by Region” or “Authors by Publications by Year”.
### filter() rows or select() columns ### 
  #Filter or select pieces of the data by row, column, or both.
### mutate() ###
  # Mutate the data by creating new variables at the current level of grouping.
### summarize() ### 
  #Summarize or aggregate the grouped data.
    # For example we might calculate means with mean() or counts with n().


```


```{r}
rel_by_region <- gss_sm %>%
    group_by( bigregion, religion ) %>% 
    summarize( N = n() ) %>% # counts the number for each group
    mutate( freq = N / sum(N),
            pct = round((freq*100), 0) )
rel_by_region
```


```{r}
# Check if the above pipe operator worked well
rel_by_region %>% group_by(bigregion) %>%
  summarize(total = sum(pct))
```


```{r}
p <- ggplot(rel_by_region, aes(x = bigregion, y = pct, fill = religion))

# geom_col vs geom_bar: geom_col has a default value of stat='identity'
p + geom_col(position = "dodge2") + # use dodge2 instead of dodge: gives space between each bar
    labs(x = "Region",y = "Percent", fill = "Religion") +
    theme(legend.position = "top")
```

```{r}
p <- ggplot(rel_by_region, aes(x = religion, y = pct, fill = religion))

p + geom_col(position = "dodge2") +
    labs(x = NULL, y = "Percent", fill = "Religion") +
    guides(fill = "none") + 
    coord_flip() + 
    facet_grid(~ bigregion)
```

```{r}
?organdata
glimpse(organdata)
skim(organdata)
view(organdata)
```



########################################################################
Continuous variables by group or category
########################################################################


```{r}
p <- ggplot(data = organdata,
            mapping = aes(x = year, y = donors))
p + geom_point()

```

```{r}
p <- ggplot(data = organdata,
            mapping = aes(x = country, y = donors, na.rm=TRUE))
p + geom_boxplot() + coord_flip()
```

```{r}
p <- ggplot(data = organdata,
            mapping = aes(x = reorder(country, donors, na.rm=TRUE),
                          y = donors))
p + geom_boxplot() +
    labs(x=NULL) +
    coord_flip()
```


```{r}
```

```{r}
# geom_boint

p <- ggplot(data = organdata,
            mapping = aes(x = reorder(country, donors, na.rm=TRUE),
                          y = donors, fill = world))
p + geom_boxplot() + labs(x=NULL) +
    coord_flip() + theme(legend.position = "top")




p <- ggplot(data = organdata,
            mapping = aes(x = reorder(country, donors, na.rm=TRUE),
                          y = donors, color = world))
p + geom_point(alpha = .5) + labs(x=NULL) +
    coord_flip() + theme(legend.position = "top")

p + geom_jitter(position = position_jitter(width=0.15)) +
    labs(x=NULL) + coord_flip() + theme(legend.position = "top")


# Boxplot is a better visualization
```

```{r}
# geom_jitter
p <- ggplot(data = organdata,
            mapping = aes(x = reorder(country, donors, na.rm=TRUE),
                          y = donors, color = world))


# consider using geom_violin with geom_jitter
```

```{r}
by_country <- organdata %>% group_by(consent_law, country) %>%
    summarize(donors_mean= mean(donors, na.rm = TRUE),
              donors_sd = sd(donors, na.rm = TRUE),
              gdp_mean = mean(gdp, na.rm = TRUE),
              health_mean = mean(health, na.rm = TRUE),
              roads_mean = mean(roads, na.rm = TRUE),
              cerebvas_mean = mean(cerebvas, na.rm = TRUE))

# OR
by_country <- organdata %>% group_by(consent_law, country) %>%
    summarize_if(is.numeric, funs(mean, sd), na.rm = TRUE) %>%
    ungroup()

by_country
```

########################################################################
Cleveland dotplot
########################################################################


```{r}
p <- ggplot(data = by_country,
            mapping = aes(x = donors_mean, y = reorder(country, donors_mean),
                          color = consent_law))
p + geom_point(size=3) +
    labs(x = "Donor Procurement Rate",
         y = "", color = "Consent Law") +
    theme(legend.position="top")
```

```{r}
p <- ggplot(data = by_country,
            mapping = aes(x = donors_mean,
                          y = reorder(country, donors_mean)))

p + geom_point(size=3) +
    facet_wrap(~ consent_law, scales = "free_y", ncol = 1) + # scales = "free_y" eliminates countries that are not included in the data
    labs(x= "Donor Procurement Rate",
         y= "") 
```

```{r}
p <- ggplot(data = by_country, mapping = aes(x = reorder(country,
              donors_mean), y = donors_mean))

p + geom_pointrange(mapping = aes(ymin = donors_mean - donors_sd,
       ymax = donors_mean + donors_sd)) +
     labs(x= "", y= "Donor Procurement Rate") + coord_flip()

```
########################################################################
Plot text directly 
########################################################################

```{r}
p <- ggplot(data = by_country,
            mapping = aes(x = roads_mean, y = donors_mean))

p + geom_point() + geom_text(mapping = aes(label = country))

# or 

p + geom_point() + geom_text(mapping = aes(label = country), hjust = 1.1)
```


########################################################################
Historical U.S. presidential election data
########################################################################

```{r}
# Data
?elections_historic
glimpse(elections_historic)
skim(elections_historic)
view(elections_historic)

```

```{r}
p_title <- "Presidential Elections: Popular & Electoral College Margins"
p_subtitle <- "1824-2016"
p_caption <- "Data for 2016 are provisional."
x_label <- "Winner's share of Popular Vote"
y_label <- "Winner's share of Electoral College Votes"

p <- ggplot(elections_historic, aes(x = popular_pct, y = ec_pct,
                                    label = winner_label))

p + geom_hline(yintercept = 0.5, size = 1.4, color = "gray80") +  # We use two new geoms, `geom_hline()` and `geom_vline()` to make the lines. 
    geom_vline(xintercept = 0.5, size = 1.4, color = "gray80") +
    geom_point() +
    geom_text_repel() +  # `geom_text_repel()` makes sure the labels do not overlap with each other, or obscure other points.
    scale_x_continuous(labels = scales::percent) +
    scale_y_continuous(labels = scales::percent) +
    labs(x = x_label, y = y_label, title = p_title, subtitle = p_subtitle,
         caption = p_caption)
```

